import React, { useState, useEffect } from 'react';

const StravaHeatmap = () => {
    const [mockData, setMockData] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const loadStravaData = async () => {
            try {
                // Fetch the static json file dynamically generated by our background script
                // Appending a timestamp query forces cache bypass if the user refreshes
                const res = await fetch(`/strava-data.json?t=${new Date().getTime()}`);
                if (!res.ok) throw new Error('Data file not found');
                const data = await res.json();
                setMockData(data);
            } catch (err) {
                console.warn('Could not load real Strava data, falling back to empty state:', err);
                // Construct empty layout for skeleton
                const emptyData = [];
                const today = new Date();
                const startDate = new Date(today);
                startDate.setDate(today.getDate() - (52 * 7));
                
                let currentDate = new Date(startDate);
                while (currentDate <= today) {
                    emptyData.push({
                        date: currentDate.toISOString().split('T')[0],
                        count: 0,
                        kcal: 0,
                        duration: 0
                    });
                    currentDate.setDate(currentDate.getDate() + 1);
                }
                setMockData(emptyData);
            } finally {
                setLoading(false);
            }
        };

        loadStravaData();
    }, []);

    // Calculate intensity level (0-4) based on kcal AND count
    const getIntensity = (kcal, count) => {
        if (count === 0) return 0;
        if (kcal === 0 && count > 0) return 1; // Activity done, but no calories tracked
        if (kcal < 400) return 1;
        if (kcal < 800) return 2;
        if (kcal < 1200) return 3;
        return 4;
    };

    // Color map adapted to the current minimalist/apple aesthetic
    const colorMap = {
        0: 'bg-black/5 dark:bg-white/5', 
        1: 'bg-[#9FB6CD]/30 dark:bg-[#9FB6CD]/40', 
        2: 'bg-[#9FB6CD]/70 dark:bg-[#9FB6CD]/80', 
        3: 'bg-[#E1A2B8]/80 dark:bg-[#E1A2B8]/90',       
        4: 'bg-[#E1A2B8] dark:bg-[#f29bbb]',                                      
    };

    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    
    // Calculate weeks count dynamically
    const columnsCount = Math.ceil(mockData.length / 7);

    return (
        <div className="w-full flex flex-col gap-6 mt-16 mb-8 group/strava">
            <div className="flex flex-col gap-1">
                <h3 className="text-2xl font-semibold tracking-tight text-gray-900 dark:text-gray-100 flex items-center gap-3">
                    <svg className="w-6 h-6 text-[#FC4C02] flex-shrink-0" viewBox="0 0 24 24" fill="currentColor">
                        <path d="M15.387 17.944l-2.089-4.116h-3.065L15.387 24l5.15-10.172h-3.066m-7.008-5.599l2.836 5.598h4.172L10.463 0l-7 13.828h4.169" />
                    </svg>
                    Activity
                </h3>
                <p className="text-gray-500 dark:text-gray-400">A reflection of my effort over the past year.</p>
            </div>
            
            <div className="p-4 sm:p-6 bg-white/40 dark:bg-black/20 backdrop-blur-xl rounded-[1.5rem] sm:rounded-[2rem] border border-gray-200/50 dark:border-white/5 shadow-sm transition-colors duration-500 w-full">
                
                {/* 12 Months Spread Evenly */}
                <div className="flex justify-between w-full text-[10px] md:text-xs text-gray-400 font-mono mb-2 px-1">
                    {months.map(m => <span key={m}>{m}</span>)}
                </div>

                {/* The scaling CSS Grid (No horizontal overflow/scroll anymore) */}
                <div 
                    className="w-full grid grid-rows-7 gap-[2px] sm:gap-[3px] md:gap-1"
                    style={{ 
                        gridAutoFlow: 'column', 
                        gridTemplateColumns: `repeat(${columnsCount}, minmax(0, 1fr))` 
                    }}
                >
                    {mockData.map((dayData, index) => {
                        const intensity = getIntensity(dayData.kcal, dayData.count);
                        
                        return (
                            <div 
                                key={index} 
                                className={`aspect-square w-full rounded-[2px] sm:rounded-[3px] ${colorMap[intensity]} hover:ring-[1px] sm:hover:ring-2 hover:ring-gray-300 dark:hover:ring-gray-400 hover:scale-[1.2] transition-all duration-200 cursor-crosshair relative group/day`}
                            >
                                {/* Tooltip on Hover */}
                                <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-max px-3 py-1.5 bg-black/95 dark:bg-white/95 text-white dark:text-black text-[10px] sm:text-xs rounded-xl opacity-0 group-hover/day:opacity-100 pointer-events-none transition-all duration-200 scale-95 group-hover/day:scale-100 z-50 flex flex-col items-center shadow-xl border border-white/10 dark:border-black/10 origin-bottom">
                                    <span className="font-semibold">{dayData.date}</span>
                                    {dayData.count > 0 ? (
                                        <span className="opacity-80 mt-0.5 font-mono">{dayData.count} activities • {dayData.kcal} kcal</span>
                                    ) : (
                                        <span className="opacity-50 mt-0.5">Rest day</span>
                                    )}
                                </div>
                            </div>
                        );
                    })}
                </div>
                
                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mt-5 sm:mt-6 text-[10px] sm:text-xs text-gray-500 dark:text-gray-400 font-mono gap-3 sm:gap-0">
                    <div className="flex gap-4">
                        <span className="flex items-center gap-1.5">
                            <span className="font-semibold text-gray-900 dark:text-gray-100">{mockData.filter(d => d.count > 0).length}</span> active days
                        </span>
                        <span className="flex items-center gap-1.5">
                            <span className="font-semibold text-gray-900 dark:text-gray-100">
                                {mockData.reduce((acc, d) => acc + d.kcal, 0).toLocaleString()}
                            </span> kcal
                        </span>
                    </div>
                    
                    <div className="flex items-center gap-1.5">
                        <span className="mr-1">Less</span>
                        {[0, 1, 2, 3, 4].map(level => (
                            <div key={level} className={`w-3 h-3 sm:w-3.5 sm:h-3.5 rounded-[2px] sm:rounded-[3px] ${colorMap[level]}`} />
                        ))}
                        <span className="ml-1">More</span>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default StravaHeatmap;
