import React, { useState, useEffect } from 'react';

const StravaHeatmap = () => {
    const [mockData, setMockData] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const loadStravaData = async () => {
            try {
                // Fetch the static json file dynamically generated by our background script
                // Appending a timestamp query forces cache bypass if the user refreshes
                const baseUrl = import.meta.env.BASE_URL;
                const path = baseUrl.endsWith('/') ? baseUrl + 'strava-data.json' : baseUrl + '/strava-data.json';
                const res = await fetch(`${path}?t=${new Date().getTime()}`);
                if (!res.ok) throw new Error('Data file not found');
                const data = await res.json();
                setMockData(data);
            } catch (err) {
                console.warn('Could not load real Strava data, falling back to empty state:', err);

                // Construct empty layout for skeleton exactly like github grid constraints
                const emptyData = [];
                const today = new Date();
                const dayOfWeek = today.getDay(); // 0 (Sun) to 6 (Sat)
                const totalDays = (52 * 7) + (dayOfWeek + 1);
                const startDate = new Date(today);
                startDate.setDate(today.getDate() - totalDays + 1);

                let currentDate = new Date(startDate);
                while (currentDate <= today) {
                    emptyData.push({
                        date: currentDate.toISOString().split('T')[0],
                        count: 0,
                        kcal: 0,
                        duration: 0
                    });
                    currentDate.setDate(currentDate.getDate() + 1);
                }
                setMockData(emptyData);
            } finally {
                setLoading(false);
            }
        };

        loadStravaData();
    }, []);

    // Calculate intensity level (0-4) based on duration AND count
    const getIntensity = (duration, count) => {
        if (count === 0) return 0;
        if (duration === 0 && count > 0) return 1; // Activity done, but no time tracked
        if (duration <= 30) return 1; // Up to 30 mins
        if (duration <= 60) return 2; // Up to 1 hour
        if (duration <= 90) return 3; // Up to 1h 30m
        return 4; // More than 1h 30m
    };

    // Color map adapted to the current minimalist/apple aesthetic on a pure white background
    const colorMap = {
        0: 'bg-[#F3F4F6] shadow-sm border border-black/5 dark:border-white/5 dark:bg-[#161B22]',
        1: 'bg-[#9FB6CD]/40 dark:bg-[#9FB6CD]/50 border border-black/5 dark:border-transparent',
        2: 'bg-[#9FB6CD]/80 dark:bg-[#9FB6CD]/80 border border-black/5 dark:border-transparent',
        3: 'bg-[#E1A2B8]/90 dark:bg-[#E1A2B8]/90 border border-black/5 dark:border-transparent',
        4: 'bg-[#E1A2B8] dark:bg-[#f29bbb] border border-black/5 dark:border-transparent',
    };

    const months = [];
    const today = new Date();
    for (let i = 11; i >= 0; i--) {
        const d = new Date(today.getFullYear(), today.getMonth() - i, 1);
        months.push(d.toLocaleString('en-US', { month: 'short' }));
    }

    // Calculate weeks count dynamically
    const columnsCount = Math.ceil(mockData.length / 7);

    return (
        <div className="w-full flex flex-col gap-6 mt-16 mb-8 group/strava">
            <div className="flex flex-col gap-1">
                <h3 className="text-2xl font-semibold tracking-tight text-primary flex items-center gap-3">
                    Strava activities
                </h3>
                <p className="text-gray-500 dark:text-gray-400">A reflection of my physical effort over the past year.</p>
            </div>

            <div className="p-4 sm:p-6 bg-white dark:bg-[#0A0A0A] backdrop-blur-xl rounded-[1.5rem] sm:rounded-[2rem] border border-gray-100 dark:border-white/5 shadow-apple transition-colors duration-500 w-full relative">

                <div className="flex gap-2 sm:gap-3 w-full">
                    {/* Days of Week Y-Axis */}
                    <div className="hidden sm:flex flex-col text-[10px] text-gray-400 font-mono mt-[20px] md:mt-[24px] mb-[1px] gap-[2px] sm:gap-[3px] md:gap-1"
                        style={{ justifyContent: 'space-between' }}>
                        <span className="leading-none">Sun</span>
                        <span className="leading-none">Mon</span>
                        <span className="leading-none">Tue</span>
                        <span className="leading-none">Wed</span>
                        <span className="leading-none">Thu</span>
                        <span className="leading-none">Fri</span>
                        <span className="leading-none">Sat</span>
                    </div>

                    <div className="flex-1 w-full flex flex-col">
                        {/* 12 Months Spread Evenly */}
                        <div className="flex justify-between w-full text-[10px] md:text-xs text-gray-400 font-mono mb-2 px-1">
                            {months.map((m, idx) => <span key={idx}>{m}</span>)}
                        </div>

                        {/* The scaling CSS Grid with arbitrary Tailwind class grid-rows-[7] */}
                        <div
                            className="w-full grid gap-[2px] sm:gap-[3px] md:gap-1 flex-1"
                            style={{
                                gridAutoFlow: 'column',
                                gridTemplateRows: 'repeat(7, minmax(0, 1fr))',
                                gridTemplateColumns: `repeat(${columnsCount}, minmax(0, 1fr))`
                            }}
                        >
                            {mockData.map((dayData, index) => {
                                const intensity = getIntensity(dayData.duration, dayData.count);

                                return (
                                    <div
                                        key={index}
                                        className={`aspect-square w-full rounded-[2px] sm:rounded-[3px] ${colorMap[intensity]} hover:ring-[1px] sm:hover:ring-2 hover:ring-gray-300 dark:hover:ring-gray-400 hover:scale-[1.2] transition-all duration-200 cursor-crosshair relative group/day z-10 hover:z-20`}
                                    >
                                        {/* Tooltip on Hover */}
                                        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-max px-3 py-1.5 bg-gray-900 dark:bg-white text-white dark:text-gray-900 text-[10px] sm:text-xs rounded-xl opacity-0 group-hover/day:opacity-100 pointer-events-none transition-all duration-200 scale-95 group-hover/day:scale-100 z-50 flex flex-col items-center shadow-xl border border-black/10 dark:border-white/10 origin-bottom">
                                            <span className="font-semibold">{dayData.date}</span>
                                            {dayData.count > 0 ? (
                                                <span className="opacity-90 mt-0.5 font-mono">
                                                    {dayData.count} act{dayData.count > 1 ? 's' : ''} • {dayData.duration}m
                                                    {dayData.kcal > 0 && ` • ${dayData.kcal} kcal`}
                                                </span>
                                            ) : (
                                                <span className="opacity-60 mt-0.5">Rest day</span>
                                            )}
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>
                </div>

                <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mt-5 sm:mt-6 text-[10px] sm:text-xs text-gray-500 dark:text-gray-400 font-mono gap-3 sm:gap-0">
                    <div className="flex gap-4">
                        <span className="flex items-center gap-1.5">
                            <span className="font-semibold text-gray-900 dark:text-gray-100">{mockData.filter(d => d.count > 0).length}</span> active days
                        </span>
                        <span className="flex items-center gap-1.5">
                            <span className="font-semibold text-gray-900 dark:text-gray-100">
                                {Math.round(mockData.reduce((acc, d) => acc + d.duration, 0) / 60).toLocaleString()}
                            </span> hours trained
                        </span>
                    </div>

                    <div className="flex items-center gap-1.5">
                        <span className="mr-1">Less</span>
                        {[0, 1, 2, 3, 4].map(level => (
                            <div key={level} className={`w-3 h-3 sm:w-3.5 sm:h-3.5 rounded-[2px] sm:rounded-[3px] ${colorMap[level]}`} />
                        ))}
                        <span className="ml-1">More</span>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default StravaHeatmap;
